name: 刷课
 
on: 
  push:
    branches: [ main ]
  #是否开始每天8点定时刷课，若要开启请把下面两行注释去掉
  #schedule:
  #  - cron: "0 8 * * *" 
    
jobs: 
  Start:
    runs-on: ubuntu-latest # 在最新版本的 Ubuntu 操作系统环境下运行
    steps: # 要执行的步骤
      - name: 拷贝代码
        uses: actions/checkout@v4  # 用于将github代码仓库的代码拷贝到工作目录中
 
      - name: 设置python环境
        uses: actions/setup-python@v5 # 用于设置 Python 环境，它允许你指定要在工作环境中使用的 Python 版本
        with:
          python-version: '3.13'  # 选择要用的Python版本
 
      - name: 安装依赖包
        run: | # 安装依赖包
          pip install -r ./requirements.txt 
          
      
      - name: Run main.py
        env:
         CHAOXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
         CHAOXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
         CHAOXING_COURSE_LIST: ${{ secrets.CHAOXING_COURSE_LIST }}
        run: python main.py -u "$CHAOXING_USERNAME" -p "$CHAOXING_PASSWORD" -l "$CHAOXING_COURSE_LIST"
